import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const step = async (n, f) => { try { await f(); console.log("OK " + n); } catch (e) { console.log("FAIL " + n + " :: " + e.message.split("\n")[0]); } };
await page.goto("http://localhost:5215/");
await step(1, () => page.waitForSelector("text=授权码登录", { timeout: 10000 }));
await step(2, () => page.locator('input[type="password"]').fill("ainiyiwannian"));
await step(3, () => page.getByRole("button", { name: "进入游戏" }).click());
await step(4, () => page.waitForSelector('button:has-text("人口")', { timeout: 30000 }));
await step(5, () => page.getByRole("button", { name: "世界地图" }).click());
await step(6, () => page.getByRole("button", { name: "全国" }).click());
await step(7, () => page.locator('[data-province="gx"]').click());
await step(8, () => page.locator('[data-city="baise"]').click({ timeout: 8000 }));
await page.waitForTimeout(1000);
const body = await page.locator("body").innerText();
const i = body.indexOf("驻守将领");
console.log("C4 百色驻守段: " + (i >= 0 ? body.slice(i, i + 120).replace(/\n/g, " ") : "NOT FOUND"));
await browser.close();
