// 省级元数据：id / 名称 / 省会坐标（全国层投影用）/ 真实省界接壤（海路标记 SEA）
export const PROVINCES_RAW = [
  { id: 'bj', name: '北京', lat: 39.9, lon: 116.4, neighbors: ['tj', 'he'] },
  { id: 'tj', name: '天津', lat: 39.1, lon: 117.2, neighbors: ['bj', 'he'] },
  { id: 'sh', name: '上海', lat: 31.23, lon: 121.47, neighbors: ['js', 'zj'] },
  { id: 'cq', name: '重庆', lat: 29.56, lon: 106.55, neighbors: ['sc', 'gz', 'hn', 'hb', 'sn'] },
  { id: 'he', name: '河北', lat: 38.04, lon: 114.5, neighbors: ['bj', 'tj', 'sx', 'nm', 'ln', 'sd', 'ha'] },
  { id: 'sx', name: '山西', lat: 37.87, lon: 112.55, neighbors: ['he', 'nm', 'sn', 'ha'] },
  { id: 'nm', name: '内蒙古', lat: 40.84, lon: 111.75, neighbors: ['hl', 'jl', 'ln', 'he', 'sx', 'sn', 'nx', 'gs'] },
  { id: 'ln', name: '辽宁', lat: 41.8, lon: 123.43, neighbors: ['jl', 'nm', 'he'] },
  { id: 'jl', name: '吉林', lat: 43.9, lon: 125.32, neighbors: ['hl', 'nm', 'ln'] },
  { id: 'hl', name: '黑龙江', lat: 45.8, lon: 126.63, neighbors: ['nm', 'jl'] },
  { id: 'js', name: '江苏', lat: 32.06, lon: 118.8, neighbors: ['sh', 'zj', 'ah', 'sd'] },
  { id: 'zj', name: '浙江', lat: 30.28, lon: 120.15, neighbors: ['sh', 'js', 'ah', 'jx', 'fj'] },
  { id: 'ah', name: '安徽', lat: 31.82, lon: 117.23, neighbors: ['js', 'zj', 'jx', 'hb', 'ha', 'sd'] },
  { id: 'fj', name: '福建', lat: 26.08, lon: 119.3, neighbors: ['zj', 'jx', 'gd', 'tw|SEA'] },
  { id: 'jx', name: '江西', lat: 28.68, lon: 115.86, neighbors: ['fj', 'zj', 'ah', 'hb', 'hn', 'gd'] },
  { id: 'sd', name: '山东', lat: 36.65, lon: 117.12, neighbors: ['he', 'ha', 'ah', 'js'] },
  { id: 'ha', name: '河南', lat: 34.75, lon: 113.63, neighbors: ['he', 'sx', 'sn', 'hb', 'ah', 'sd'] },
  { id: 'hb', name: '湖北', lat: 30.59, lon: 114.3, neighbors: ['ha', 'ah', 'jx', 'hn', 'cq', 'sn'] },
  { id: 'hn', name: '湖南', lat: 28.23, lon: 112.94, neighbors: ['hb', 'jx', 'gd', 'gx', 'gz', 'cq'] },
  { id: 'gd', name: '广东', lat: 23.13, lon: 113.26, neighbors: ['fj', 'jx', 'hn', 'gx', 'hi|SEA', 'hk', 'mo'] },
  { id: 'gx', name: '广西', lat: 22.82, lon: 108.32, neighbors: ['gd', 'hn', 'gz', 'yn', 'hi|SEA'] },
  { id: 'hi', name: '海南', lat: 20.04, lon: 110.32, neighbors: ['gd|SEA', 'gx|SEA'] },
  { id: 'sc', name: '四川', lat: 30.57, lon: 104.07, neighbors: ['cq', 'gz', 'yn', 'xz', 'qh', 'gs', 'sn'] },
  { id: 'gz', name: '贵州', lat: 26.65, lon: 106.63, neighbors: ['sc', 'yn', 'gx', 'hn', 'cq'] },
  { id: 'yn', name: '云南', lat: 24.88, lon: 102.83, neighbors: ['sc', 'gz', 'gx', 'xz'] },
  { id: 'xz', name: '西藏', lat: 29.65, lon: 91.14, neighbors: ['sc', 'yn', 'qh', 'xj'] },
  { id: 'sn', name: '陕西', lat: 34.34, lon: 108.94, neighbors: ['sx', 'ha', 'hb', 'sc', 'gs', 'nx', 'nm'] },
  { id: 'gs', name: '甘肃', lat: 36.06, lon: 103.83, neighbors: ['sn', 'nx', 'nm', 'qh', 'xj', 'sc'] },
  { id: 'qh', name: '青海', lat: 36.62, lon: 101.78, neighbors: ['gs', 'sc', 'xz', 'xj'] },
  { id: 'nx', name: '宁夏', lat: 38.49, lon: 106.23, neighbors: ['sn', 'gs', 'nm'] },
  { id: 'xj', name: '新疆', lat: 43.83, lon: 87.62, neighbors: ['gs', 'qh', 'xz'] },
  { id: 'hk', name: '香港', lat: 22.32, lon: 114.17, neighbors: ['gd'] },
  { id: 'mo', name: '澳门', lat: 22.2, lon: 113.55, neighbors: ['gd'] },
  { id: 'tw', name: '台湾', lat: 25.03, lon: 121.56, neighbors: ['fj|SEA'] },
];
